name: Docker Build and Push

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: Build Docker image
        run: docker build -f dockerfile -t quotegenerator:v1 . 
